# Generated by Django 5.0.1 on 2024-10-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childentity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='childentity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='dependententity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='dependententity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='extendedentity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='extendedentity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
        migrations.AlterField(
            model_name='parententity',
            name='dt_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Creation time'),
        ),
        migrations.AlterField(
            model_name='parententity',
            name='dt_updated',
            field=models.DateTimeField(auto_now=True, db_index=True, verbose_name='Update time'),
        ),
    ]
