# Generated by Django 5.0.1 on 2024-10-05 00:11

from django.db import migrations, models
from django.utils.translation import gettext_lazy as _



class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dt_first_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date/time of first login'),
        ),
    ]
